name: ci

on:
  push:
    branches: main

env:
  GHP_TAG: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:latest

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --tag "$GHP_TAG" .

      - name: Login to Github Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Publish image to GitHub Packages
        run: docker push "$GHP_TAG"

